# Solarized Dark for Kitty, tuned to match the vendored Naysayer Neovim theme.

foreground               #d0b892
background               #062625

selection_foreground     #ffffff
selection_background     #0000ff

cursor                   #ffffff
cursor_text_color        #062625

url_color                #66D9EF

color0   #123b3d
color1   #F92672
color2   #A6E22E
color3   #E6DB74
color4   #66D9EF
color5   #FD5FF0
color6   #A1EFE4
color7   #d0b892
color8   #126367
color9   #ff0000
color10  #53d549
color11  #ffaa00
color12  #87ffde
color13  #AE81FF
color14  #3ad0b5
color15  #ffffff

active_tab_foreground    #12251b
active_tab_background    #d3b58e
inactive_tab_foreground  #126367
inactive_tab_background  #062625
