foreground              #f8f8f2
background              #000000
selection_foreground    #ffffff
selection_background    #008097
cursor                  #f8f8f0
cursor_text_color       #000000
url_color               #4ecdc4
active_border_color     #aee239
inactive_border_color   #737b84
bell_border_color       #e61f44
color0                  #151515
color1                  #e61f44
color2                  #8fbe00
color3                  #e9ee00
color4                  #00a8c6
color5                  #f7b83d
color6                  #4ecdc4
color7                  #f8f8f2
color8                  #737b84
color9                  #ff4262
color10                 #aee239
color11                 #ffe792
color12                 #4ecdc4
color13                 #c8d7e8
color14                 #00a8c6
color15                 #ffffff
