[main]
font=IosevkaTerm Nerd Font:size=17
## font=FiraCode Nerd Font:size=17
pad = 16x16
selection-target=both

[scrollback]
lines=100000

[colors-dark]
# Naysayer Theme Palette
background=062329
foreground=d1b897
cursor=062329 ffffff

## Normal/regular colors
regular0=062329  # black (background)
regular1=f92672  # red (naysayer-theme-red)
regular2=44b340  # green (comments color)
regular3=fd971f  # yellow/orange (naysayer-theme-orange)
regular4=66d9ef  # blue (naysayer-theme-blue)
regular5=ae81ff  # magenta/violet (naysayer-theme-violet)
regular6=2ec09c  # cyan (strings color)
regular7=d1b897  # white (text color)

## Bright colors
bright0=126367   # bright black (line-fg / dark gray-green)
bright1=ff0000   # bright red (error)
bright2=a6e22e   # bright green (naysayer-theme-green)
bright3=e6db74   # bright yellow (naysayer-theme-yellow)
bright4=c1d1e3   # bright blue (variables/methods color)
bright5=fd5ff0   # bright magenta (naysayer-theme-magenta)
bright6=a1efe4   # bright cyan (naysayer-theme-cyan)
bright7=ffffff   # bright white (white / keywords)

## Selecting and highlights
selection-background=0000ff
selection-foreground=ffffff
urls=7ad0c6
