[main]
include=~/.config/tsp-theme/current/foot.ini
font=IosevkaTerm Nerd Font:size=13
## font=FiraCode Nerd Font:size=13
pad = 16x16
selection-target=both

[scrollback]
lines=100000

[text-bindings]
# Make Ctrl+Backspace behave like Ctrl+W (delete the previous word).
\x17=Control+BackSpace
