;;; ginger-bill-theme.el --- Freshcut Contrast desktop theme -*- lexical-binding: t; -*-
(deftheme ginger-bill "Freshcut Contrast adapted as Ginger Bill.")
(let ((bg "#000000") (bg-alt "#151515") (fg "#f8f8f2")
      (muted "#737b84") (red "#e61f44") (green "#aee239")
      (yellow "#e9ee00") (blue "#00a8c6") (cyan "#4ecdc4")
      (cool "#c8d7e8") (orange "#f7b83d"))
  (custom-theme-set-faces
   'ginger-bill
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background "#f8f8f0"))))
   `(fringe ((t (:background ,bg :foreground ,muted))))
   `(region ((t (:background "#008097" :foreground "#ffffff"))))
   `(highlight ((t (:background ,bg-alt :foreground ,fg))))
   `(font-lock-builtin-face ((t (:foreground ,cyan))))
   `(font-lock-comment-face ((t (:foreground ,muted))))
   `(font-lock-constant-face ((t (:foreground ,blue))))
   `(font-lock-function-name-face ((t (:foreground ,green))))
   `(font-lock-keyword-face ((t (:foreground ,cool))))
   `(font-lock-string-face ((t (:foreground ,yellow))))
   `(font-lock-type-face ((t (:foreground ,cyan))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,orange :weight bold))))
   `(success ((t (:foreground ,green))))
   `(mode-line ((t (:background "#008097" :foreground "#ffffff" :box nil))))
   `(mode-line-inactive ((t (:background ,bg-alt :foreground ,muted :box nil))))
   `(minibuffer-prompt ((t (:foreground ,green :weight bold))))
   `(link ((t (:foreground ,cyan :underline t))))))
(provide-theme 'ginger-bill)
;;; ginger-bill-theme.el ends here
