;;; gruber-tsoding-theme.el --- Gruber Darker Tsoding desktop theme -*- lexical-binding: t; -*-
(deftheme gruber-tsoding "Gruber Darker palette inspired by Tsoding.")
(let ((bg "#181818") (bg-dark "#101010") (fg "#e4e4ef")
      (muted "#565f73") (red "#f43841") (green "#73c936")
      (yellow "#ffdd33") (blue "#96a6c8") (purple "#9e95c7")
      (cyan "#95a99f") (brown "#cc8c3c"))
  (custom-theme-set-faces
   'gruber-tsoding
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,yellow))))
   `(fringe ((t (:background ,bg :foreground ,muted))))
   `(region ((t (:background "#484848" :foreground ,fg))))
   `(highlight ((t (:background "#282828" :foreground ,fg))))
   `(font-lock-builtin-face ((t (:foreground ,cyan))))
   `(font-lock-comment-face ((t (:foreground ,brown :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,purple))))
   `(font-lock-function-name-face ((t (:foreground ,blue))))
   `(font-lock-keyword-face ((t (:foreground ,yellow :weight bold))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,cyan))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,yellow :weight bold))))
   `(success ((t (:foreground ,green))))
   `(mode-line ((t (:background "#52494e" :foreground ,fg :box nil))))
   `(mode-line-inactive ((t (:background ,bg-dark :foreground ,muted :box nil))))
   `(minibuffer-prompt ((t (:foreground ,yellow :weight bold))))
   `(link ((t (:foreground ,blue :underline t))))))
(provide-theme 'gruber-tsoding)
;;; gruber-tsoding-theme.el ends here
