include theme.conf
background_image none
window_padding_width 10 15 10 15

# font_family IoskeleyMonoTerm Nerd Font
# font_features "IoskeleyMonoTerm Nerd Font" -liga

font_family IosevkaTerm Nerd Font
font_features IosevkaTermNF -liga

font_size 17

confirm_os_window_close 0
cursor_shape block

# Enable cursor trail (number determines length of trail)
cursor_trail 1
cursor_trail_decay 0.01 0.5
cursor_trail_start_threshold 0

# Optional: Customize the behavior
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 1
shell_integration no-cursor

disable_ligatures always
enable_audio_bell no
pixel_scroll yes
copy_on_select yes


map ctrl+shift+enter launch --cwd=current
map ctrl+shift+s launch --type=background --allow-remote-control sh -c 'exec "$HOME/.config/kitty/switch-theme"'


# doing tabs

allow_remote_control yes
listen_on unix:/tmp/kitty-main
tab_bar_edge top
tab_bar_style custom
tab_separator       ""
tab_title_template  " {index} {title} "
tab_bar_min_tabs 1
active_tab_foreground    #E4E4E4
active_tab_background    #181818
inactive_tab_foreground  #95A99F
inactive_tab_background  #282828
macos_option_as_alt no
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

enabled_layouts splits
map ctrl+shift+t new_tab_with_cwd
map alt+shift+v launch --location=vsplit --cwd=current
map alt+shift+m launch --location=hsplit --cwd=current
map alt+shift+h neighboring_window left
map alt+shift+l neighboring_window right
map alt+shift+k neighboring_window up
map alt+shift+j neighboring_window down
map alt+shift+w close_window
map alt+shift+u resize_window narrower
map alt+shift+i resize_window wider
