# Gruber Darker for Kitty
# -----------------------
# Theme author: John Gruber (https://daringfireball.net/projects/bbcolors/schemes/)
# Ported by: blazkowolf & vieitesss
# Upstream: https://github.com/blazkowolf/gruber-darker.nvim/blob/main/extras/kitty/gruber-darker.conf

foreground               #E4E4E4
background               #000000

selection_foreground     #F4F4FF
selection_background     #453D41

cursor                   #FFDD33
cursor_text_color        #181818

url_color                #96A6C8

# black
color0   #181818
color8   #52494E

# red
color1   #F43841
color9   #F43841

# green
color2   #73D936
color10  #73D936

# yellow
color3   #FFDD33
color11  #FFDD33

# blue
color4   #96A6C8
color12  #96A6C8

# magenta
color5   #9E95C7
color13  #9E95C7

# cyan (aqua)
color6   #95A99F
color14  #95A99F

# white / light gray
color7   #F5F5F5
color15  #FFFFFF


background_opacity 0.70
background_blur 15
background_image none
padding_width 8
padding_height 6
window_padding_width 10 15 10 15

font_family IoskeleyMonoTerm Nerd Font
font_features "IoskeleyMonoTerm Nerd Font" -liga

# font_family Monolisa
font_size 15

confirm_os_window_close 0
cursor_shape block

# Enable cursor trail (number determines length of trail)
cursor_trail 10

# Optional: Customize the behavior
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 1
shell_integration no-cursor

disable_ligatures always
enable_audio_bell no
pixel_scroll yes


map ctrl+shift+enter launch --cwd=current


# doing tabs

allow_remote_control yes
listen_on unix:/tmp/kitty-main
tab_bar_edge top
tab_bar_style custom
tab_separator       ""
tab_title_template  " {index} {title} "
tab_bar_min_tabs 1
active_tab_foreground    #E4E4E4
active_tab_background    #181818
inactive_tab_foreground  #95A99F
inactive_tab_background  #282828
macos_option_as_alt no

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

enabled_layouts splits
map alt+v launch --location=vsplit --cwd=current
map alt+m launch --location=hsplit --cwd=current
map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down
map alt+w close_window
map alt+u resize_window narrower
map alt+i resize_window wider
