[[entries]]
origin = "Home"
key = ".zshrc"
profiles = [
    "desktop-arch",
    "laptop-arch",
]

[[entries]]
origin = "XdgConfig"
key = "kitty"
profiles = [
    "desktop-arch",
    "laptop-arch",
]

[[entries]]
origin = "XdgConfig"
key = "nvim"
profiles = [
    "desktop-arch",
    "laptop-arch",
]

[[entries]]
origin = "XdgConfig"
key = "emacs"
profiles = [
    "desktop-arch",
    "laptop-arch",
]

[[entries]]
origin = "XdgConfig"
key = "helix"
profiles = [
    "desktop-arch",
    "laptop-arch",
]
