accent = "#66d9ef"
cursor = "#ffffff"
foreground = "#d1b897"
background = "#062329"
selection_foreground = "#ffffff"
selection_background = "#0000ff"
muted = "#126367"
color0 = "#062329"
color1 = "#f92672"
color2 = "#44b340"
color3 = "#fd971f"
color4 = "#66d9ef"
color5 = "#ae81ff"
color6 = "#2ec09c"
color7 = "#d1b897"
color8 = "#126367"
color9 = "#ff0000"
color10 = "#a6e22e"
color11 = "#e6db74"
color12 = "#c1d1e3"
color13 = "#fd5ff0"
color14 = "#a1efe4"
color15 = "#ffffff"

