accent = "#ffdd33"
cursor = "#ffdd33"
foreground = "#e4e4ef"
background = "#181818"
selection_foreground = "#181818"
selection_background = "#484848"
muted = "#565f73"
color0 = "#484848"
color1 = "#c73c3f"
color2 = "#73c936"
color3 = "#ffdd33"
color4 = "#96a6c8"
color5 = "#9e95c7"
color6 = "#95a99f"
color7 = "#e4e4ef"
color8 = "#52494e"
color9 = "#f43841"
color10 = "#73c936"
color11 = "#ffdd33"
color12 = "#96a6c8"
color13 = "#9e95c7"
color14 = "#95a99f"
color15 = "#f4f4ff"
